from fastapi import APIRouter
from app.models.schemas import QuizRequest, QuizResponse, QuizQuestion

router = APIRouter(prefix="/api/v1/quiz", tags=["quiz"])


@router.post("/", response_model=QuizResponse)
async def generate_quiz(request: QuizRequest):
    """
    Quiz generation endpoint.
    Retrieves relevant course material via RAG, generates pedagogical quiz questions.
    """
    # TODO: Week 2 - RAG retrieval for course material
    # TODO: Week 4 - LLM quiz generation with structured output
    placeholder_questions = [
        QuizQuestion(
            question=f"[Placeholder] Question about {request.topic}?",
            options=["Option A", "Option B", "Option C", "Option D"],
            correct_index=0,
            explanation="This will be generated by the LLM based on retrieved course material.",
        )
        for _ in range(min(request.num_questions, 5))
    ]

    return QuizResponse(
        questions=placeholder_questions,
        topic=request.topic,
        total_questions=len(placeholder_questions),
    )
